### PR TITLE
Unit test for Package java.util.function

### PR DESCRIPTION
**Pull request by gaurangkudale**
Added the unit test for a Unit test for java.util.function

### CODE REVIEW

**Comment by gaurangkudale** [comment]
Hi @cyrille-artho,
Here I've added the unit test for `java.util.function` where it contains multiple Interfaces #306 please check it out and let me know if do you have any suggestions

**Comment by gaurangkudale** [comment]
Hi @cyrille-artho,
Any updates?

**Comment by cyrille-artho** [comment]
Looks good. Your pull request still has the commit messages from older commits, so perhaps you have to rebase your forked repository on the merged changes in this repository again.
This doesn't affect your PR, as I can remove these messages before the merge.

**Comment by gaurangkudale** [comment]
@cyrille-artho [https://github.com/javapathfinder/jpf-core/wiki/GSoC-2021-Project-Ideas#support-java-11-bootstrap-methods-and-other-issues-for-jpf-core](url)
I want to work on this project can you please guide me?

**Comment by gaurangkudale** [comment]
> @cyrille-artho [https://github.com/javapathfinder/jpf-core/wiki/GSoC-2021-Project-Ideas#support-java-11-bootstrap-methods-and-other-issues-for-jpf-core](url)
> I really want to work on this project can you please guide me? 

I guess this project is still not completed 
I'll try my best to complete this

**Comment by cyrille-artho** [comment]
This functionality is mostly complete, but some advanced use cases and special cases do not work correctly.
You can for example look at issue #258 .
However, fixing this issue requires changes deep inside JVM's main code that implements how the VM interprets such bootstrap method calls.

**Comment by gaurangkudale** [comment]
@cyrille-artho  
What about the unit tests for java 8 Do we required more unit tests for all other packages? If yes then I'll first complete the unit tests support for java 8

**Comment by cyrille-artho** [comment]
Not sure what else needs to be tested; you can perhaps find more things to test by looking at web pages that describe features that were introduced in Java 8 or Java 11 (as there are probably also some features for Java 11 that we also need to test).
For Java 11, we use the branch `java-10-gradle`. It might be a good idea to rename that branch to `java-11` to avoid confusion; the branch was created before Java 11 came out.

**Comment by gaurangkudale** [comment]
Can we talk on other platforms such as discord of javapathfinder or anywhere else because We are facing lag because of difference in time zones

**Comment by gaurangkudale** [comment]
> This functionality is mostly complete, but some advanced use cases and special cases do not work correctly.
> You can for example look at issue #258 .
> However, fixing this issue requires changes deep inside JVM's main code that implements how the VM interprets such bootstrap method calls.

What about Java 12 support project is it also completed? If not where can I get started with that project under your guidance

**Pull request merged**
