### PR TITLE
Create toShortSignature() in Method.java

### PR DESCRIPTION
**Pull request by eklaDFF**
Created `toShortSignature()` in `Method.java`

### CODE REVIEW

**Comment by cyrille-artho** [comment]
Hi,
This PR does not fix any additional failing test. We had 14 failing tests before and now. Can you please check again?

**Comment by eklaDFF** [comment]
Actually this is leading error after repeat() method in String

**Comment by eklaDFF** [comment]
Fixing this might solve the 4-5 failing test cases.

**Comment by cyrille-artho** [comment]
How many failing tests do you have locally? The patch for `repeat` is already in JPF at this point, so perhaps this patch does not affect any additional features? Is there a test that failed before but works now? Perhaps the patch breaks a test that passed earlier (possibly for the wrong reason such as an incomplete check of the resulting state/output)?

**Comment by eklaDFF** [comment]
Currently there is 14 failing test cases. The method repeat() solved two failing test case reducing total failed test cases to 14. No, there is not any test cases that failed before and now work.

**Comment by eklaDFF** [comment]
Yeh, I think we should move forward with this.
Please review the changes in GitHub repo attached above and let me know
what you think.

**Comment by eklaDFF** [comment]
A. Error report without implementing `toShortSignature()` in `Method.java`

```
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.NoSuchMethodError: java.lang.reflect.Method.toShortSignature()Ljava/lang/String;
	at java.lang.reflect.ProxyGenerator$ProxyMethod.<init>(ProxyGenerator.java:711)
	at java.lang.reflect.ProxyGenerator.<clinit>(ProxyGenerator.java:108)
	at java.lang.reflect.Proxy.getProxyClass(Proxy.java:73)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:85)
	at gov.nasa.jpf.test.vm.reflection.ProxyTest.testBasicProxy(ProxyTest.java:60)
	at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)
```
B. Error report after implementing `toShortSignature()` in `Method.java`

```
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.NoSuchMethodError: java.lang.Class.descriptorString()Ljava/lang/String;
	at sun.invoke.util.BytecodeDescriptor.unparseSig(BytecodeDescriptor.java:155)
	at sun.invoke.util.BytecodeDescriptor.unparseMethod(BytecodeDescriptor.java:144)
	at java.lang.invoke.MethodType.toMethodDescriptorString(MethodType.java:1190)
	at java.lang.reflect.ProxyGenerator$ProxyMethod.generateMethod(ProxyGenerator.java:721)
	at java.lang.reflect.ProxyGenerator.generateClassFile(ProxyGenerator.java:500)
	at java.lang.reflect.ProxyGenerator.generateProxyClass(ProxyGenerator.java:178)
	at java.lang.reflect.Proxy.getProxyClass(Proxy.java:73)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:85)
	at gov.nasa.jpf.test.vm.reflection.ProxyTest.testBasicProxy(ProxyTest.java:60)
	at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)
```

In A, our error is reported while it is at static block and in B our error is reported way ahead.

**Comment by cyrille-artho** [comment]
Thank you for your explanation. I'll merge this as a partial fix for that test case (and I don't see a need to create a smaller test case where only the first function is needed).

**Pull request merged**
