### PR TITLE
Revert "Format output of ant 'test' target"

### PR DESCRIPTION
**Pull request by gayanW**
Reverts javapathfinder/jpf-core#48

### CODE REVIEW

**Comment by gayanW** [comment]
@cyrille-artho Sure I'll look into it. 

In our JUnit task printsummary is set to on. However as the `forkmode` is set to `perTest`, test result summary is printed per test. I'll see if there's a workaround to get it to output the final result.

https://github.com/javapathfinder/jpf-core/blob/a83107dbb0e5959d13c4be1121afed37cfa8c74a/build.xml#L447-L449

**Comment by cyrille-artho** [comment]
In that case, why not just turn off forkmode.
We can afford to lose some time, and we'll try to get the best and most efficient configuration later, for the gradle-supported build.

**Comment by gayanW** [comment]
It looks like forking is necessary. When turned off, failure of one test seems to cause all subsequent tests fail.

As for the test outputs what about generating a HTML report for Junit results? In that case we could inspect log outputs, errs per each test in a browser locally without cluttering the console output. I think it would be good to do it in a separate PR.

**Comment by cyrille-artho** [comment]
OK, then let's leave the configuration as by this PR.
There is no need to look into this further, as the gradle build will already updated the test output.

**Pull request merged**
