### PR TITLE
Fixed missing ClassNotFoundException for invalid array types due to incomplete checks in the method Types.getClassNameFromTypeName() (#204)

### PR DESCRIPTION
**Pull request by rtrimana**
1) Added a fix for the method `Types.getClassNameFromTypeName()`.
2) Added a unit test to test that this fix can catch the invalid array type with a `java.lang.ClassNotFoundException`.

Please see this [issue ](https://github.com/javapathfinder/jpf-core/issues/204) for further explanation about the problem.

### CODE REVIEW

**Comment by rtrimana** [comment]
@cyrille-artho BTW, I apologize for the included commits that you have squash-merged before in this pull request. Please let me know if I need to re-fork the repository on my local or you can actually select specific commits for this pull request.

**Comment by cyrille-artho** [comment]
@rtrimana : No problem, I just wanted to document _why_ I removed parts of the commit messages.
It is a good idea that you commented each commit. As I was squashing (combining) all commits into one, messages that refer to commits that cancel a previous edit no longer make sense, so I removed those.

**Comment by cyrille-artho** [comment]
Thank you very much for your detailed explanations and the patch!

**Comment by rtrimana** [comment]
You're welcome! It's my pleasure and thanks for letting me contribute to the JPF project.

**Pull request merged**
