### PR TITLE
shoaib/issue#439

### PR DESCRIPTION
**Pull request by sshaikshoaib**
i have changed .equals function to .compareTo function. hope it works

### CODE REVIEW

**Comment by cyrille-artho** [comment]
Thank you for your implementation. Please also provide a unit test so we know that the new version of the code works as intended. See the wiki for instructions on how to write unit tests: https://github.com/javapathfinder/jpf-core/wiki/Writing-JPF-tests

**Review by cyrille-artho — CHANGES_REQUESTED** [review]
Please add a unit test, as this part of the code is currently not covered by a test, so we don't know if your change fixes the issue.

**Comment by sshaikshoaib** [comment]
Hi @cyrille-artho I am a beginner and I have a good knowledge on java.so i used this knowledge to rectify the issue.
so give me some time as Iam a beginner I don't know how to write test cases.
But i have an Immense interest in contributing to java projects.so can you just me how to write test cases

**Comment by sshaikshoaib** [comment]
i have added the required tests for the updated code. please revies that and suggest me if any updates required

**Comment by cyrille-artho** [comment]
Hi,
Thank you for the test. It fails, which means the test shows the problem with the typecast not happening as expected, but the code change in the main code does not fix the bug yet.

**Comment by cyrille-artho** [comment]
Thanks! This patch seems to fix the problem. To merge it, can you please remove the extra file `.vscode/settings.json`? You accidentally added it, and you can simply use `git rm -f .vscode/settings.json` followed by a commit on your branch (shoaib/issue#439) to remove it. Once you push that change, this pull request will be updated automatically.

**Comment by cyrille-artho** [comment]
Subsumed by #491

**Pull request closed without merging**
