### PR TITLE
Added Unit test example 

### PR DESCRIPTION
**Pull request by gaurangkudale**
Added `IntStream` example to `src\tests\StreamTest`

### CODE REVIEW

**Comment by gaurangkudale** [comment]
Hi @cyrille-artho 
I don't know why it is showing previous commits will it affect this PR?

**Comment by cyrille-artho** [comment]
You probably have to pull the earlier changes from `javapathfinder:master` first. This will bring your fork up to date with the main repository.

**Comment by gaurangkudale** [comment]
So unit test example is right or do I need any modifications>

**Comment by cyrille-artho** [comment]
As for the test itself, it should automatically verify something (without using `print`). The easiest way is to have a local counter `i` that runs alongside the final stage of the stream, and you check at each step that the value from the stream is the same as the value of the counter (while incrementing the counter). This way, we have a simple way to test that the stream returns all numbers in sequence (if used sequentially).

**Pull request closed without merging**
