### PR TITLE
Indentation and grammatical corrrections

### PR DESCRIPTION
**Pull request by Eeshan8503**
Improvised documentation for better understanding
:)

### CODE REVIEW

**Comment by cyrille-artho** [comment]
Hi,
Thank you for the improvement. I would like to merge your changes, but "the wiki" is actually fine; please remove the two instances where you changed that to "wiki", and keep the other changes. You can make these changes on your forked repo and push again to there; this will update the PR.

**Comment by Eeshan8503** [comment]
@cyrille-artho thank you for paying attention to my contribution
will change that right away
thanx :)

**Comment by Eeshan8503** [comment]
@cyrille-artho I've look up and made the required changes 
I request you to merge my PR into the main branch
thanx :)

**Comment by cyrille-artho** [comment]
Thanks. There is one more thing I did not catch earlier: If you replace "look at the 'How to install JPF' guide" with "look at 'How to install JPF using the link provided' guide", you will have to remove "guide". Furthermore, the extra text "using the link provided" is not needed, as the link is visible as such.
Please remove these two changes (or all the changes in the first paragraph), and then I will gladly merge your remaining changes.

**Comment by Eeshan8503** [comment]
@cyrille-artho 
After going through the document I've improvised again 
please look into the changes I've made.
I'll be more than happy if there's anything else I can do.
:)

**Comment by cyrille-artho** [comment]
Thank you very much! Merged.

**Pull request merged**
